import { ORIGINS, PATHS, ADVENTURES, byID } from './data.js';
import { AdventureEngine, CombatEngine, SkillCheckHelper, createHero, useHealingDraught } from './engines.js';
const originsByID = byID(ORIGINS); const pathsByID = byID(PATHS); let hero;
const $ = id => document.getElementById(id);
function option(value, text) { const node = document.createElement('option'); node.value = value; node.textContent = text; return node; }
function log(line, tone = '') { $('log').insertAdjacentHTML('afterbegin', `<p class="${tone}">${line}</p>`); }
function renderHero() { if (!hero) return; const path = pathsByID[hero.path], origin = originsByID[hero.origin]; $('heroTitle').textContent = `${hero.name}, ${path.name}`; $('heroMeta').innerHTML = `${path.role}<br><span class="pill">${origin.name}: ${origin.feature}</span>`; $('stats').innerHTML = `<div class=stat>HP<b>${hero.currentHealth}/${hero.maxHealth}</b></div><div class=stat>Defence<b>${hero.defence}</b></div><div class=stat>Gold<b>${hero.gold}</b></div><div class=stat>XP<b>${hero.xp}</b></div>` + Object.entries(hero.attributes).map(([key, value]) => `<div class=stat>${key}<b>${value}</b></div>`).join(''); $('abilities').innerHTML = hero.abilities.map(ability => `<span class="pill">${ability}</span>`).join('') + `<span class="pill">${hero.inventory['Minor Healing Draught'] ?? 0} healing draughts</span>`; }
function renderRoom() { if (!hero) return; const room = AdventureEngine.currentRoom(hero); $('roomKicker').textContent = ADVENTURES[0].title; $('sceneTitle').textContent = room.title; $('sceneText').textContent = room.description; $('combat').innerHTML = hero.combatState?.phase === 'heroTurn' ? hero.combatState.enemies.map(enemy => `<h3>${enemy.name}</h3><div class=bar><span style="width:${100 * enemy.currentHealth / enemy.maxHealth}%"></span></div><p class=subtitle>HP ${enemy.currentHealth}/${enemy.maxHealth} • Defence ${enemy.defence}</p>`).join('') : ''; const buttons = []; if (room.type === 'combat' || room.type === 'boss') buttons.push(`<button class="choice" data-action="combat">Fight</button>`); if (room.type === 'skillCheck') buttons.push(`<button class="choice" data-action="skill">Attempt ${room.skill} (${room.target})</button>`); for (const choice of room.choices ?? []) buttons.push(`<button class="choice" data-action="choice" data-next="${choice.nextRoomID}" data-skill="${choice.skill ?? ''}" data-target="${choice.target ?? ''}">${choice.text}</button>`); buttons.push('<button class="choice" data-action="heal">Use Minor Healing Draught</button>'); $('choices').innerHTML = buttons.join(''); }
function render() { renderHero(); renderRoom(); }
function finishRoom(nextRoomID) { if (!nextRoomID) { AdventureEngine.complete(hero); $('sceneTitle').textContent = 'Quest Complete'; $('sceneText').textContent = `${hero.name} returns to Greywick with ${hero.gold} gold and ${hero.xp} XP.`; $('choices').innerHTML = '<button data-action="new">Play Again</button>'; log('Victory! Greywick is safer tonight.', 'gold'); renderHero(); return; } AdventureEngine.moveTo(hero, nextRoomID); hero.combatState = null; render(); }
function handleCombat() { const room = AdventureEngine.currentRoom(hero); if (!hero.combatState) CombatEngine.startCombat(hero, room); CombatEngine.runRound(hero); for (const entry of hero.combatState.log.splice(0)) log(entry, entry.includes('hits') ? 'bad' : ''); if (hero.combatState.phase === 'victory') { const reward = CombatEngine.collectRewards(hero); log(`Won combat: +${reward.xp} XP and +${reward.gold} gold.`, 'gold'); finishRoom(room.nextRoomID); } else if (hero.combatState.phase === 'defeated') { $('sceneTitle').textContent = 'You fell in the dark'; $('sceneText').textContent = 'Start a new game to try again.'; $('choices').innerHTML = '<button data-action="new">New Game</button>'; log('Defeat!', 'bad'); } render(); }
function handleSkill(room, skill, target, next) { const result = SkillCheckHelper.check(hero, skill, Number(target)); log(`${skill} check: ${result.total} vs ${target}. ${result.success ? 'Success.' : 'Failure.'}`, result.success ? 'good' : 'bad'); finishRoom(next ?? room.nextRoomID); }
function start() { hero = createHero({ name: $('heroName').value || 'Hero', origin: originsByID[$('origin').value], path: pathsByID[$('path').value] }); AdventureEngine.startAdventure(hero, ADVENTURES[0].id); $('log').innerHTML = ''; log(`${hero.name} begins ${ADVENTURES[0].title}.`, 'gold'); render(); }
function init() { for (const origin of ORIGINS) $('origin').append(option(origin.id, origin.name)); for (const path of PATHS) $('path').append(option(path.id, path.name)); $('start').addEventListener('click', start); $('newGameTop').addEventListener('click', start); $('choices').addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; const action = button.dataset.action; if (action === 'new') { start(); return; } const room = AdventureEngine.currentRoom(hero); if (action === 'combat') handleCombat(); if (action === 'skill') handleSkill(room, room.skill, room.target, room.nextRoomID); if (action === 'choice') button.dataset.skill ? handleSkill(room, button.dataset.skill, button.dataset.target, button.dataset.next) : finishRoom(button.dataset.next); if (action === 'heal') { log(useHealingDraught(hero), 'good'); render(); } }); $('choices').innerHTML = '<button class="choice" data-action="new">Start Adventure</button>'; }
init();
